# Dockerfile for PostgreSQL Database Initialization
FROM postgres:15

# set the environment variable for the timezone
ENV TZ=Asia/Shanghai

# copy the SQL initialization script into the Docker image
COPY init.sql /docker-entrypoint-initdb.d/